### ISSUE TITLE
Receive links shared from others apps using PWA Web Share Target API

### ISSUE THREAD

**Issue by ni554n** [wukko/cobalt#252]
Cobalt is the perfect app to use this API and it's pretty straightforward to implement. Currently, it only supports Chrome-based browsers, but as it'll save several clicks, I think it's worth it to consider.

[Receiving shared data with the Web Share Target API](https://developer.chrome.com/en/articles/web-share-target/)
[Share data between apps](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Share_data_between_apps)
[manifest.share_target](https://developer.mozilla.org/en-US/docs/Web/Manifest/share_target)

**Comment by wukko** [comment]
receiving doesn't work for anything but android chrome, but even then their own sample pwa never worked properly on my android phone. i would love to do it, but it's simply impossible for now :(

**Comment by Mattis142** [comment]
I know I have said this before on Twitter but maybe it'd be better on here for tracking requests but could you please check again if it works for you now? because the demo they supplied certainly works for me

Android 14 (AP21.240216.010)
Chrome version 122.0.6261.119
Webview Version 123.0.6312.40 (631204042)

if you throw a URL at it, it simply works 
![Screenshot_20240316-203904](https://github.com/wukko/cobalt/assets/40364718/fff7af51-e578-4ea5-abd5-88b4d5852c08)
![Screenshot_20240316-203826](https://github.com/wukko/cobalt/assets/40364718/c7ff3a10-1fd3-4679-9d07-657c7c55a665)

**Comment by yerrak00** [comment]
@wukko I was able to get it to work with my phone and PC, I opened up PR #404  for it.
