### ISSUE TITLE
Videos downloaded are incredibly long

### ISSUE THREAD

**Issue by RealDaku** [wukko/cobalt#56]
For some reason, any time i download a video from youtube, the video is registered as extremely long, for example, one video i had downloaded was listed as being 256204778 hours long (or 29247 years). While the video file does not take up much space, on average being about 1.5 mb for a 15 second video, it is impossible to share it to any other services without getting a file size warning.

**Comment by wukko** [comment]
this is caused by live render functionality. ffmpeg simply cannot predict output file length while sending headers. try using other players (such as one that is built into any desktop web browser), and see if issue persists, because those are able to detect video length properly.

![image](https://user-images.githubusercontent.com/71202418/208229169-fc915975-f94b-48e6-b77d-83a461d03c60.png)
