### ISSUE TITLE
add croatian to crowdin

### ISSUE THREAD

**Issue by SomeCuteDoragons** [wukko/cobalt#70]
I would like to contribute by translating cobalt into Croatian

**Comment by kresimirko** [comment]
Are there any updates on this? I'd also like to contribute.

**Comment by kresimirko** [comment]
after a while, I've decided to (finally) finish my translations. they're not the greatest and I did set up a few issues, but that's probably fine since they have to be verified anyway

_also, a note: I probably won't be using this GitHub account anymore and I might start contributing under a different one_
